# Generated by Django 4.2.1 on 2023-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_clothes_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='photo',
            field=models.CharField(max_length=350),
        ),
    ]
