# Generated by Django 4.2.1 on 2023-05-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_clothes_pre_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='photo',
            new_name='pre_photo',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='description',
        ),
    ]
