# Generated by Django 4.2.1 on 2023-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_size_clothes_description_clothes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
